import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure

    documentationSideBar: [
        {
            type: 'autogenerated',
            dirName: 'documentacao'
        }
    ],
    integrationsSideBar: [
        {
            type: 'autogenerated',
            dirName: 'integracoes'
        }
    ],
    cityHallsSidebar: [
        {
            type: 'autogenerated',
            dirName: 'prefeituras'
        }
    ],
    legislationSidebar: [
        {
            type: 'autogenerated',
            dirName: 'legislacao'
        }
    ],
    openApiSidebar: [
        'rest-api/intro',
        {
            type: "category",
            label: "Consulta de CPF (V1)",
            link: {
                type: "generated-index",
                title: "Consulta de CPF",
                description: "Conheça a API de Consulta de CPF da NFe.io, que permite validar e obter informações detalhadas sobre números de CPF (Cadastro de Pessoas Físicas) no Brasil. Nossa API é fácil de usar e integra-se perfeitamente com suas aplicações, oferecendo dados precisos e atualizados para ajudar na verificação de identidade, prevenção de fraudes e melhoria da experiência do usuário.",
                slug: "/rest-api/consulta-de-cpf-v1"
            },
            items: require("./docs/rest-api/consulta-de-cpf-v1/sidebar.js")
        },
        {
            type: "category",
            label: "Consulta de Nota Fiscal (V2)",
            link: {
                type: "generated-index",
                title: "Consulta de Nota Fiscal (V2)",
                description: "Facilite a verificação e autenticação de notas fiscais eletrônicas (NF-e) emitidas no Brasil com a API de Consulta de Nota Fiscal da NFe.io. Nossa API oferece uma maneira rápida e eficiente de acessar informações detalhadas sobre NF-e, incluindo status, detalhes do emissor, valores e itens, garantindo conformidade fiscal e simplificando processos administrativos para empresas de todos os tamanhos.",
                slug: "/rest-api/consulta-de-nota-fiscal-v2"
            },
            items: require("./docs/rest-api/consulta-de-nota-fiscal-v2/sidebar.js")
        },
        {
            type: "category",
            label: "Consulta de Nota Fiscal de Consumidor (V1)",
            link: {
                type: "generated-index",
                title: "Consulta de Nota Fiscal de Consumidor",
                description: "Conheça a API de Consulta de Nota Fiscal de Consumidor (NFC-e) da NFe.io, que permite verificar e obter informações detalhadas sobre notas fiscais eletrônicas emitidas para consumidores finais no Brasil. Nossa API é fácil de integrar e oferece dados precisos e atualizados, facilitando a gestão fiscal, a conformidade regulatória e a melhoria da experiência do cliente para empresas varejistas.",
                slug: "/rest-api/consulta-de-nota-fiscal-consumidor-v1"
            },
            items: require("./docs/rest-api/consulta-de-nota-fiscal-consumidor-v1/sidebar.js")
        },
        {
            type: "category",
            label: "Consulta de CNPJ (V2)",
            link: {
                type: "generated-index",
                title: "Consulta de CNPJ (V2)",
                description: "Consulte e valide informações de empresas brasileiras com a API de Consulta de CNPJ da NFe.io. Nossa API oferece acesso rápido e fácil a dados atualizados sobre o Cadastro Nacional da Pessoa Jurídica (CNPJ), incluindo detalhes como razão social, endereço, situação cadastral e atividades econômicas. Ideal para empresas que buscam melhorar seus processos de verificação de fornecedores, clientes e parceiros comerciais.",
                slug: "/rest-api/consulta-de-cnpj-v1"
            },
            items: require("./docs/rest-api/consulta-de-cnpj-v1/sidebar.js")
        },
        {
            type: "category",
            label: "Consulta de Endereços (V2)",
            link: {
                type: "generated-index",
                title: "Consulta de Endereços",
                description: "A API de Consulta de Endereços da NFe.io permite buscar e validar endereços no Brasil de forma rápida e eficiente. Com acesso a uma base de dados abrangente, nossa API facilita a verificação de CEPs, logradouros, bairros, cidades e estados, garantindo que suas operações comerciais e logísticas sejam precisas e confiáveis. Ideal para empresas que desejam melhorar a qualidade dos dados de endereço em seus sistemas.",
                slug: "/rest-api/consulta-de-enderecos-v1"
            },
            items: require("./docs/rest-api/consulta-de-enderecos-v1/sidebar.js")
        },
        {
            type: "category",
            label: "Nota Fiscal de Consumidor (V2)",
            link: {
                type: "generated-index",
                title: "Nota Fiscal de Consumidor",
                description: "API de Emissão de Nota Fiscal de Consumidor Eletrônica (NFC-e) da NFe.io, que permite a emissão rápida e segura de notas fiscais eletrônicas para consumidores finais no Brasil. Nossa API é fácil de integrar e oferece conformidade total com as regulamentações fiscais, facilitando a gestão de vendas no varejo e melhorando a experiência do cliente.",
                slug: "/rest-api/nota-fiscal-de-consumidor-v2"
            },
            items: require("./docs/rest-api/nota-fiscal-de-consumidor-v2/sidebar.js")
        },
        {
            type: "category",
            label: "Nota Fiscal de Produto (v2)",
            link: {
                type: "generated-index",
                title: "Nota Fiscal de Produto (v2)",
                description: "API de Emissão de Nota Fiscal Eletrônica (NF-e) da NFe.io, que permite a emissão rápida e segura de notas fiscais eletrônicas para produtos no Brasil. Nossa API é fácil de integrar e oferece conformidade total com as regulamentações fiscais, facilitando a gestão de vendas, estoque e logística para empresas de todos os tamanhos.",
                slug: "/rest-api/nota-fiscal-de-produto-v2"
            },
            items: require("./docs/rest-api/nota-fiscal-de-produto-v2/sidebar.js")
        },
        {
            type: "category",
            label: "Calculo de Impostos (V1)",
            link: {
                type: "generated-index",
                title: "Cálculo de Impostos",
                description: "API de Cálculo de Impostos da NFe.io, que oferece uma solução eficiente para calcular tributos federais, estaduais e municipais no Brasil. Nossa API é projetada para simplificar a complexidade do sistema tributário brasileiro, permitindo que empresas de todos os tamanhos realizem cálculos precisos de impostos como ICMS, IPI, PIS, COFINS e ISS, garantindo conformidade fiscal e otimizando processos financeiros.",
                slug: "/rest-api/calculo-de-impostos-v1"
            },
            items: require("./docs/rest-api/calculo-de-impostos-v1/sidebar.js")
        },
        {
            type: "category",
            label: "Nota Fiscal de Serviço (V1)",
            link: {
                type: "generated-index",
                title: "Nota Fiscal de Serviço",
                description: "API de Emissão de Nota Fiscal de Serviço Eletrônica (NFS-e) da NFe.io, que permite a emissão rápida e segura de notas fiscais eletrônicas para serviços no Brasil. Nossa API é fácil de integrar e oferece conformidade total com as regulamentações fiscais municipais, facilitando a gestão de serviços prestados e melhorando a eficiência administrativa para empresas de todos os tamanhos.",
                slug: "/rest-api/nota-fiscal-de-servico-v1"
            },
            items: require("./docs/rest-api/nota-fiscal-de-servico-v1/sidebar.js")
        },
        {
            type: "category",
            label: "Consulta de CT-e (v2)",
            link: {
                type: "generated-index",
                title: "Consulta de CT-e (Distribuição)",
                description: "API de Consulta de Conhecimento de Transporte Eletrônico (CT-e) da NFe.io permite verificar e obter informações detalhadas sobre CT-e emitidos no Brasil. Nossa API oferece uma maneira rápida e eficiente de acessar dados essenciais, como status, detalhes do emissor, valores e serviços de transporte, garantindo conformidade fiscal e simplificando processos logísticos para empresas de transporte e logística.",
                slug: "/rest-api/consulta-de-ct-e-v2"
            },
            items: require("./docs/rest-api/consulta-de-ct-e-v2/sidebar.js")
        },
        {
            type: "category",
            label: "Consulta NF-e Distribuição",
            link: {
                type: "generated-index",
                title: "Consulta de NF-e (Distribuição)",
                description:
                    "API de Consulta de Nota Fiscal Eletrônica (NF-e) por Distribuição da NFe.io, que permite acessar e obter informações detalhadas sobre NF-e emitidas no Brasil. Nossa API facilita a consulta de notas fiscais eletrônicas através do serviço de distribuição da SEFAZ, oferecendo dados precisos e atualizados para garantir conformidade fiscal e otimizar processos administrativos para empresas de todos os tamanhos.",
                slug: "/rest-api/consulta-nf-e-distribuicao"
            },
            items: require("./docs/rest-api/consulta-nf-e-distribuicao-v1/sidebar.js")
        },
    ]
};

export default sidebars;
